<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>RiverSealTrigger</groupId>
  <artifactId>RiverSealTrigger</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <properties>
		<javafx.version>21</javafx.version>
  </properties>
  <build>
    <sourceDirectory>src</sourceDirectory>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <release>17</release>
        </configuration>
      </plugin>
      					<!-- Set up javafx properly.  -->
					<plugin>
						<groupId>org.openjfx</groupId>
						<artifactId>javafx-maven-plugin</artifactId>
						<version>0.0.8</version>
					</plugin>
    </plugins>
  </build>
  <dependencies>
	<!-- https://mvnrepository.com/artifact/gov.nist.math/jama -->
  	<dependency>
  		<groupId>gov.nist.math</groupId>
  		<artifactId>jama</artifactId>
  		<version>1.0.3</version>
  	</dependency>
  			<!--  IMPORTANT - IF MAVEN IS NOT DOWNLOADING THE JAVAFX FILES AND
		INSTEAD THROWING AN ERROR, IT MIGHT BE BECAUSE THERE IS AN
		INTERFERENCE WITH JAMIE'S REPOSITORY.  I'm not sure why this happens,
		but it does.  To fix, comment out the repository (in
		the <repositories> section above, let Maven download the JavaFX
		files, and then uncomment the repository again.    -->
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-controls</artifactId>
			<version>${javafx.version}</version>
		</dependency>

  </dependencies>
</project>